name: fastai2_audio
channels:
- fastai
- pytorch
- conda-forge
- defaults
dependencies:
- fastprogress
- jupyter
- librosa
- matplotlib
- pandas
- pillow==6.1
- pip
- python>=3.6
- pytorch==1.3.1
- pyyaml
- requests
- scikit-learn
- scipy
- spacy
- torchaudio>=0.3
- torchvision
- pip:
    - fastai2
    - colorednoise

